name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-workflow:
    name: Test workflow
    runs-on: ubuntu-latest
    steps:
      - name: 01-Checkout
        uses: actions/checkout@v4
      - name: 02-Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=22.6.0'
      - name: 03-Install pnpm
        uses: pnpm/action-setup@v4
      - name: 04-Install dependencies
        run: pnpm install
      - name: 05-Run tests
        run: pnpm coverage
      - name: 06-Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/coverage-final.json
      - name: 07-Generate images Test via Docker
        # Run the local action defined in the `action.yml` file
        # It will build the Docker image and run the `start.sh` script
        uses: ./
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "✅ Test by waka-chart-action"
          BRANCH_NAME: "test"
          IMAGES_FOLDER: "generated"
          GIT_USER_EMAIL: "mamboer@gmail.com"
          GIT_USER_NAME: "Levin Wong"
